#BUILD := build-$(shell $(CC) -dumpmachine)
CFLAGS = -g -Wall -Os -march=native $(INCLUDE)
CFLAGS += -MD -MP
#CFLAGS += -save-temps

$(BUILD):
	-mkdir -p $(BUILD)

$(BUILD)/$(TARGET) : $(OBJS)
	$(CC) $(LFLAGS) $^ -o $@ $(LDFLAGS)

$(OBJS) : $(BUILD)/%.o : $(SOURCE)/%.c
	$(CC) -c $(CFLAGS) $(CPPFLAGS) $< -o $@



target: $(BUILD)/$(TARGET)

clean:
	-rm -rf $(BUILD)/*.d $(BUILD)/*.o $(BUILD)/$(TARGET) *.i *.s *.o *.d



-include $(BUILD)/*.d
